markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "AImager"

author: "aimager"
atom-baseurl: "http://aimager.com"
disqus: "gopherwood"
encoding: utf-8

collections:
  nagging:
    output: true

navigations:
  - title: Nagging
    class: fa fa-comment-o
    href: /nagging.html
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
