name: "AImager"
author: "aimager"
description: "aimager's blog, php, golang, web, h5, middleware, linux"
markdown: kramdown
highlighter: rouge
permalink: /post/:year/:month/:day-:title.html
atom-baseurl: "http://blog.aimager.com"
encoding: utf-8

# plugin
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# custom
theme_name: "freshness"
theme_dir: "theme"
layouts_dir: "_theme/freshness/layouts"
includes_dir: "_theme/freshness/layouts"
footer: "<a href='http://book.aimager.com' title='book'>book</a>"
google-site-verfication: O_S8PGg7ST_LpvcgqqxqNVi-YhttDZ8gNoM1__BMQnE
baidu-site-verfication: lvkqTBHPbh
icon-path: "/aimager.png"

# array custom
collections:
  nagging:
    output: true
  wiki:
    output: true
  qa:
    output: true
  theme:
    output: true

navigations:
  - title: Nagging
    class: fa fa-comment-o
    href: /nagging.html
  - title: Wiki
    class: fa fa-wikipedia-w
    href: /wiki.html
  - title: Archive
    class: fa fa-archive
    href: /archive.html
  - title: Q&A
    class: fa fa-quora
    href: /qa.html
  # - title: Tags
  #   class: fa fa-tags
  #   href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html

social:
  name: AImager
  links:
    - https://twitter.com/aimager
    - https://www.facebook.com/AImager
    - https://github.com/AImager
    - https://www.zhihu.com/people/AImager/
    - http://weibo.com/AImager