name: "AImager"
author: "aimager"
description: "aimager's blog, php, golang, web, h5, middleware, linux"
markdown: kramdown
highlighter: rouge
permalink: /post/:year/:month/:day-:title.html
atom-baseurl: "http://blog.aimager.com"
encoding: utf-8

# plugin
plugins:
  - jekyll-seo-tag

# custom
theme_name: "freshness"
theme_dir: "theme"
layouts_dir: "_theme/freshness/_layouts" 
footer: "| <a href='http://book.aimager.com' title='book'>book</a>"
google-site-verfication: O_S8PGg7ST_LpvcgqqxqNVi-YhttDZ8gNoM1__BMQnE

# array custom
collections:
  nagging:
    output: true
  wiki:
    output: true
  theme:
    output: true

navigations:
  - title: Nagging
    class: fa fa-comment-o
    href: /nagging.html
  - title: Wiki
    class: fa fa-wiki
    href: /wiki.html
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html

social:
  name: AImager
  links:
    - https://twitter.com/aimager
    - https://www.facebook.com/AImager
    - https://github.com/AImager
    - https://www.zhihu.com/people/AImager/
    - http://weibo.com/AImager